ТЗ-9
alekslit/java-filmorate pull request #10
Opened 2023-11-03 15:36 UTC by alekslit

Создать каркас Spring Boot приложения Filmorate в соответствии с ТЗ-9

2023-11-04 09:01 UTC, avlin87 requested changes
Привет, Александр,
работа выглядит хорошо.

2023-11-05 04:20 UTC, avlin87 requested changes
Проставь, пожалуйста, тэги version для зависимостей в pom.

2023-11-05 04:20 UTC, avlin87 commented on pom.xml
> +            <scope>provided</scope>
Верни, тэг <version> и в него помести ссылку на properties с версией.
<version>${lombok.version}</version>

для каждой зависимости, пожалуйста.

2023-11-05 06:13 UTC, alekslit commented on pom.xml
> +            <scope>provided</scope>
Сделал. Почему то решил удалить их изначально)

2023-11-05 20:55 UTC, avlin87 approved these changes
Работу принимаю.

2023-11-05 22:30 UTC, merged